// [460-fork] Milestone 5 slice 2 — IndexedDB-backed write queue.
//
// Behaviour:
// - enqueue() persists a mutation and returns immediately; UI applies its
//   own optimistic local change before/after as needed.
// - process() walks every 'pending' row whose next_attempt_at is in the
//   past, fires the HTTP request, and either deletes the row on success
//   or schedules an exponential backoff retry on failure. Permanent
//   failures (4xx other than 408/429) flip status to 'failed' so the UI
//   can surface them.
// - peek() / count() drive the navbar pending badge and the future
//   conflicts panel.
//
// The HTTP transport is injected so unit tests can stub network failures
// deterministically without touching axios.

import { getDb, type QueuedMutationRecord } from './localDb'
import { scheduleSnapshot } from './offlineSnapshot'

function genId(): string {
  if (typeof crypto !== 'undefined' && 'randomUUID' in crypto) {
    return (crypto as Crypto).randomUUID()
  }
  return `mq-${Date.now()}-${Math.random().toString(36).slice(2, 12)}`
}

export type MutationMethod = 'POST' | 'PUT' | 'DELETE'

export interface EnqueueInput {
  endpoint: string
  method: MutationMethod
  payload?: unknown
  observed_updated_at?: string | null
  /** Pre-computed mutation id (for tests / UI optimism that needs to know
   *  the id ahead of time). Generated by enqueue() if absent. */
  id?: string
}

export interface MutationTransport {
  send(m: QueuedMutationRecord): Promise<TransportResult>
}

export type TransportResult =
  | { kind: 'ok'; status: number; body: unknown }
  | { kind: 'retryable'; status?: number; error: string }
  | { kind: 'permanent'; status: number; error: string }

export const BACKOFF_FIRST_DELAY_MS = 1_000
export const BACKOFF_CAP_MS = 5 * 60_000
export const MAX_ATTEMPTS = 20

export async function enqueue(input: EnqueueInput): Promise<QueuedMutationRecord> {
  const db = await getDb()
  const now = Date.now()
  const record: QueuedMutationRecord = {
    id: input.id ?? genId(),
    endpoint: input.endpoint,
    method: input.method,
    payload: input.payload ?? null,
    observed_updated_at: input.observed_updated_at ?? null,
    created_at: now,
    attempts: 0,
    next_attempt_at: now,
    last_error: null,
    status: 'pending',
  }
  await db.put('mutations', record)
  // [460-fork] Defensive auto-backup: mirror the queue to OPFS so a
  // catastrophic IndexedDB eviction (iOS storage pressure, manual
  // site-data clear) doesn't take pending writes with it.
  scheduleSnapshot()
  return record
}

export async function peek(): Promise<QueuedMutationRecord[]> {
  const db = await getDb()
  return db.getAll('mutations')
}

export async function count(status?: 'pending' | 'failed'): Promise<number> {
  const all = await peek()
  if (!status) return all.length
  return all.filter(m => m.status === status).length
}

export async function clear(): Promise<void> {
  const db = await getDb()
  await db.clear('mutations')
}

export async function process(
  transport: MutationTransport,
  now: number = Date.now(),
): Promise<{ processed: number; succeeded: number; deferred: number; failed: number }> {
  const db = await getDb()
  const all = await db.getAll('mutations')
  const due = all.filter(m => m.status === 'pending' && m.next_attempt_at <= now)

  let succeeded = 0
  let deferred = 0
  let failed = 0
  for (const m of due) {
    let result: TransportResult
    try {
      result = await transport.send(m)
    } catch (err: unknown) {
      result = { kind: 'retryable', error: err instanceof Error ? err.message : String(err) }
    }

    if (result.kind === 'ok') {
      await db.delete('mutations', m.id)
      succeeded++
      continue
    }

    const nextAttempts = m.attempts + 1
    if (result.kind === 'permanent' || nextAttempts >= MAX_ATTEMPTS) {
      const updated: QueuedMutationRecord = {
        ...m,
        attempts: nextAttempts,
        last_error: result.error,
        status: 'failed',
        next_attempt_at: Number.MAX_SAFE_INTEGER,
      }
      await db.put('mutations', updated)
      failed++
      continue
    }

    const delay = Math.min(BACKOFF_CAP_MS, BACKOFF_FIRST_DELAY_MS * Math.pow(2, nextAttempts - 1))
    const updated: QueuedMutationRecord = {
      ...m,
      attempts: nextAttempts,
      last_error: result.error,
      next_attempt_at: now + delay,
    }
    await db.put('mutations', updated)
    deferred++
  }

  // Refresh OPFS snapshot whenever the queue shape changes — that way
  // a successful drain shrinks the snapshot (ultimately deleting it)
  // and a backoff retry preserves the row.
  if (succeeded > 0 || deferred > 0 || failed > 0) scheduleSnapshot()

  return { processed: due.length, succeeded, deferred, failed }
}

/** Test-only — useful when consumer code wants to remove a known-failed
 *  mutation after the user has resolved it via the conflicts UI. */
export async function remove(id: string): Promise<void> {
  const db = await getDb()
  await db.delete('mutations', id)
}
